name: Python package

on:
    push:
        branches:
            - refs/tags/*

jobs:
  package:
    name: "Package building and publishing"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install wheel
        run: pip install wheel twine
      - name: Build packages
        run: python setup.py sdist bdist_wheel
      - name: Publish package
        run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
